services:
  - type: web
    name: splitwise-backend
    runtime: docker
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ExpenseSharing.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000